name: "Install dotnet tool"

description: "Install dotnet tool"

inputs:
  tool:
    description: "id of the dotnet tool to install (e.g. wix)"
    required: true
  version:
    description: "Version of the dotnet tool to install (e.g. 6.2.0)"
    required: true

runs:
  using: node24
  main: dist/index.cjs
