name: "Ninja"

description: "Install Ninja"

inputs:
  platform:
    description: "Platform"
    required: true
  version:
    description: "Version"
    required: true

runs:
  using: "composite"
  steps:
    - name: Download Ninja
      shell: pwsh
      run: |
        Get-Location
        gh release download ${{ inputs.version }} -p '*${{ inputs.platform }}.zip' -R ninja-build/ninja
        Expand-Archive .\ninja-${{ inputs.platform }}.zip -DestinationPath ninja
        Add-Content $env:GITHUB_PATH "$(Get-Location)\ninja"
        $env:GITHUB_PATH
        ninja --version

branding:
  color: black
  icon: download
