name: "Ninja"

description: "Install Ninja"

inputs:
  platform:
    description: "Platform"
    required: true
  version:
    description: "Version"
    required: true

runs:
  using: "composite"
  steps:
    - name: Download Ninja
      shell: pwsh
      run: |
        gh release download ${{ inputs.version }} -p '*${{ inputs.platform }}.zip' -R ninja-build/ninja
        Add-Content $env:GITHUB_PATH $(Get-Location)

branding:
  color: black
  icon: download
