name: "Install clap-info"

description: "Install clap-info"

inputs:
  version:
    description: "Version"
    required: true

runs:
  using: "composite"
  steps:
    - name: Cache
      id: cache-clap-info
      uses: actions/cache@v4
      with:
        path: |
          clap-info
        key: ${{ runner.os }}-clap-info-${{ inputs.version }}

    - name: Install clap-info
      if: steps.cache-clap-info.outputs.cache-hit != 'true'
      shell: pwsh
      run: |
        switch ("${{ runner.os }}") {
          "Windows" { $platform = "win-x64" }
          "Linux" { $platform = "linux-x64" }
          "macOS" { $platform = "mac-universal" }
          default { throw "Unsupported OS: ${{runner.os}}" }
        }
        gh release download ${{ inputs.version }} -p '*$platform.zip' -R free-audio/clap-info
        Expand-Archive .\clap-info-$platform.zip -DestinationPath clap-info
        Remove-Item .\clap-info-$platform.zip

    - name: Add to path
      shell: pwsh
      run: |
        Add-Content $env:GITHUB_PATH "$(Get-Location)\clap-info"
