name: "Developer PowerShell"
description: "Developer PowerShell"
inputs:
    arch:
        description: "Arch"
        required: false
        default: "amd64"
    host-arch:
        description: "HostArch"
        required: false
        default: "amd64"
runs:
    using: "composite"
    steps:
        - name: Set Greeting
          run: |
              $vswhere = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
              $vspath = & $vswhere -products * -latest -property installationPath
              & "$vspath\Common7\Tools\Launch-VsDevShell.ps1" -Arch $Arch -HostArch $HostArch -SkipAutomaticLocation
          shell: pwsh
          env:
              INPUT_ARCH: ${{ inputs.arch }}
              INPUT_HOSTARCH: ${{ inputs.host-arch }}
