name: "Install uv tool"

description: "Install uv tool"

inputs:
  tool:
    description: "id of the uv tool to install (e.g. clang-format)"
    required: true
  version:
    description: "Version of the uv tool to install (e.g. 21.1.0)"
    required: true

runs:
  using: node24
  main: dist/index.cjs
