name: "Install Wix"

description: "Install Wix"

inputs:
  version:
    description: "Version"
    required: true

runs:
  using: "composite"
  steps:
    - name: Cache
      id: cache-wix
      uses: actions/cache@v4
      with:
        path: |
          ~/.dotnet/tools
        key: ${{ runner.os }}-wix-${{ inputs.version }}

    - name: Install
      if: steps.cache-wix.outputs.cache-hit != 'true'
      shell: pwsh
      run: |
        dotnet tool install --global wix --version ${{ inputs.version }}
