name: "InnoSetup"

description: "Install Inno Setup"

inputs:
  version:
    description: "Version"
    required: true

runs:
  using: "composite"
  steps:
    - name: Download Inno Setup
      shell: pwsh
      run: |
        Invoke-WebRequest -Uri https://files.jrsoftware.org/is/6/innosetup-${{ inputs.version }}.exe -OutFile innosetup-${{ inputs.version }}.exe
        .\innosetup-6.5.1.exe /VERYSILENT /CURRENTUSER /DIR=innosetup-6.5.1
        Get-ChildItem
        Remove-Item innosetup-${{ inputs.version }}.exe
        Add-Content $env:GITHUB_PATH "$(Get-Location)\innosetup-${{ inputs.version }}"
        iscc
