name: "Wix"

description: "Install Wix"

inputs:
  version:
    description: "Version"
    required: true

runs:
  using: "composite"
  steps:
    - name: Cache dotnet tools
      uses: actions/cache@v4
      with:
        path: |
          ~/.nuget/packages
          ~/.dotnet/tools
        key: ${{ runner.os }}-dotnet-tools-wix-${{ inputs.version }}

    - name: Install Wix
      shell: pwsh
      run: |
        dotnet tool install --global wix --version ${{ inputs.version }}
