name: "clap-info"

description: "Install clap-info"

inputs:
  platform:
    description: "Platform"
    required: true
  version:
    description: "Version"
    required: true

runs:
  using: "composite"
  steps:
    - name: Download clap-info
      shell: pwsh
      run: |
        gh release download ${{ inputs.version }} -p '*${{ inputs.platform }}.zip' -R free-audio/clap-info
        Expand-Archive .\clap-info-${{ inputs.platform }}.zip -DestinationPath clap-info
        Remove-Item .\clap-info-${{ inputs.platform }}.zip
        Add-Content $env:GITHUB_PATH "$(Get-Location)\clap-info"
        "clap-info v$(.\clap-info\clap-info --version)"
