name: "Install clap-info"

description: "Install clap-info"

inputs:
  version:
    description: "Version"
    required: true

runs:
  using: "composite"
  steps:
    - name: Cache
      id: cache-clap-info
      uses: actions/cache@v4
      with:
        path: |
          clap-info
        key: ${{ runner.os }}-clap-info-${{ inputs.version }}

    - name: Install clap-info
      if: steps.cache-clap-info.outputs.cache-hit != 'true'
      shell: pwsh
      run: |
        gh release download ${{ inputs.version }} -p '*${{ inputs.platform }}.zip' -R free-audio/clap-info
        Expand-Archive .\clap-info-${{ inputs.platform }}.zip -DestinationPath clap-info
        Remove-Item .\clap-info-${{ inputs.platform }}.zip
        Add-Content $env:GITHUB_PATH "$(Get-Location)\clap-info"
        "clap-info v$(.\clap-info\clap-info --version)"
