name: "Install clap-validator"

description: "Install clap-validator"

inputs:
  version:
    description: "Version"
    required: true

runs:
  using: "composite"
  steps:
    - name: Cache
      id: cache-clap-validator
      uses: actions/cache@v4
      with:
        path: |
          clap-validator
        key: ${{ runner.os }}-clap-validator-${{ inputs.version }}

    - name: Install clap-validator
      if: steps.cache-clap-validator.outputs.cache-hit != 'true'
      shell: pwsh
      run: |
        gh release download ${{ inputs.version }} -p '*${{ inputs.platform }}.zip' -R free-audio/clap-validator
        Expand-Archive .\clap-validator-${{ inputs.version }}-${{ inputs.platform }}.zip -DestinationPath clap-validator
        Remove-Item .\clap-validator-${{ inputs.version }}-${{ inputs.platform }}.zip
        Add-Content $env:GITHUB_PATH "$(Get-Location)\clap-validator"
        "Ninja v$(.\clap-validator\clap-validator --version)"
