name: "Setup"

description: "GitHub Actions setup"

inputs:
  path:
    description: "Path of repo"
    required: false
    default: "repo"
  depth:
    description: "Fetch depth of repo"
    required: false
    default: "1"

runs:
  using: "composite"
  steps:
    - name: Checkout powershell-scripts
      uses: actions/checkout@v4
      with:
        repository: mthierman/powershell-scripts
        path: powershell-scripts

    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        path: ${{ inputs.path }}
        fetch-depth: ${{ inputs.fetch-depth }}

branding:
  color: orange
  icon: loader
