name: "Setup"

description: "Setup"

inputs:
  path:
    description: "Path"
    required: false
    default: "repo"
  fetch-depth:
    description: "Fetch depth"
    required: false
    default: "1"

runs:
  using: "composite"
  steps:
    - name: Checkout powershell-scripts
      uses: actions/checkout@v4
      with:
        repository: mthierman/powershell-scripts
        path: powershell-scripts

    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        path: ${{ inputs.path }}
        fetch-depth: ${{ inputs.fetch-depth }}
