name: "Setup"
description: "GitHub Actions setup"
inputs:
  repo-path:
    description: "Path of repo"
    required: false
    default: "repo"
runs:
  using: "composite"
  steps:
    - name: Checkout powershell-scripts
      uses: actions/checkout@v4
      with:
        repository: mthierman/powershell-scripts
        path: powershell-scripts

    - name: Checkout repo
      env:
        INPUT_REPO_PATH: ${{ inputs.repo-path }}
      uses: actions/checkout@v4
      with:
        path: $env:INPUT_REPO_PATH
