name: "Setup"
description: "GitHub Actions setup"
inputs:
  token:
    description: "Checkout token"
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout mthierman.pages.dev
      uses: actions/checkout@v4
      with:
        repository: mthierman/mthierman.com
        token: ${{ inputs.token }}
        path: mthierman.com
